### ISSUE TITLE
Can't build, bad containerd dependency

### ISSUE THREAD

**Issue by bclermont** [zabio3/godolint#13]
On Golang 1.5.2, when I `go build -v` on `cmd/`:

```
get "golang.org/x/crypto": found meta tag get.metaImport{Prefix:"golang.org/x/crypto", VCS:"git", RepoRoot:"https://go.googlesource.com/crypto"} at //golang.org/x/crypto?go-get=1
go: github.com/moby/buildkit@v0.6.3 requires
	github.com/containerd/containerd@v1.3.0-0.20190507210959-7c1e88399ec0: invalid pseudo-version: version before v1.3.0 would have negative patch number
```

**Comment by zabio3** [comment]
Thank you for https://github.com/zabio3/godolint/issues/12 's response. I am delighted with PR.

Since go1.13 , go broke the ability to correct the detected version number for a commit if the gomod gets it wrong. 

That means that for now when you want to import buildkit with go.mod you need to copy the replace rules buildkit uses to your go.mod file as well

```
// go.mod

replace github.com/containerd/containerd => github.com/containerd/containerd v1.3.1-0.20200227195959-4d242818bf55

replace github.com/docker/docker => github.com/docker/docker v1.4.2-0.20200227233006-38f52c9fec82
```


ref https://github.com/moby/buildkit/pull/1425#issuecomment-609220074

**Comment by zabio3** [comment]
fix https://github.com/zabio3/godolint/commit/83fd02e30eb9668dc5b7cc8dcd15122a4b08f644
